language: node_js
install:
- npm install --dev
script:
- npm run build
branches:
  only:
- master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master